# postgres database configuration
database:
  host: 192.168.64.18
  port: 5432
  username: ts_user
  password: dbpass987
  dbname: ts_db
# container cmd: container run -d --name db1 -e POSTGRES_PASSWORD=dbpass987 -p 5432:5432 postgres:18 